name: Update Games List

on:
  schedule:
    - cron: '0 5 * * *'  # 5:00 утра по Москве (UTC+3)
  workflow_dispatch:

jobs:
  update-games:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and process games data
      env:
        IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
        IGDB_CLIENT_SECRET: ${{ secrets.IGDB_CLIENT_SECRET }}
      run: |
        python3 githubworker.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update games list" && git push)
