name: Update Games List

on:
  schedule:
    - cron: '0 3 * * *'  # Запускается каждый день в 3:00 UTC
  workflow_dispatch:  

jobs:
  update-games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Fetch and process games data
      run: |
        mkdir -p data
        python3 - <<EOF
        import json
        import math
        import requests

        def fetch_games(offset, limit):
            url = "https://nu3ichego5ti2suda7prishel.uhadi.workers.dev"
            params = {"offset": offset, "limit": limit}
            response = requests.get(url, params=params)
            return response.json()

        all_games = []
        offset = 0
        limit = 5000

        while True:
            games = fetch_games(offset, limit)
            if not games:
                break
            all_games.extend(games)
            offset += limit

        total_games = len(all_games)
        games_per_file = 5000
        total_files = math.ceil(total_games / games_per_file)

        for i in range(total_files):
            start = i * games_per_file
            end = min((i + 1) * games_per_file, total_games)
            with open(f'data/games_{i+1}.json', 'w') as f:
                json.dump(all_games[start:end], f)

        index = {
            "total_games": total_games,
            "total_files": total_files,
            "last_updated": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        }
        with open('data/index.json', 'w') as f:
            json.dump(index, f)
        EOF
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update games list" && git push)
