name: Update Games List

on:
  schedule:
    - cron: '0 3 * * *'  # Запускается каждый день в 3:00 UTC
  workflow_dispatch:  # Позволяет запускать вручную

jobs:
  update-games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and process games data
      run: |
        mkdir -p data
        python3 - <<EOF
        import json
        import math
        import requests
        import time

        def fetch_games():
            url = "https://nu3ichego5ti2suda7prishel.uhadi.workers.dev"
            try:
                response = requests.get(url, timeout=30)
                response.raise_for_status()
                return response.json()
            except requests.RequestException as e:
                print(f"Error fetching games: {e}")
                return None

        print("Fetching games...")
        all_games = fetch_games()

        if all_games is None:
            print("Failed to fetch games. Exiting.")
            exit(1)

        total_games = min(len(all_games), 300000)  # Ограничиваем до 300000 игр
        all_games = all_games[:total_games]  # Обрезаем список до 300000 игр

        print(f"Total games fetched and limited to 300000: {total_games}")

        games_per_file = 5000
        total_files = math.ceil(total_games / games_per_file)

        print(f"Creating {total_files} file(s)...")

        for i in range(total_files):
            start = i * games_per_file
            end = min((i + 1) * games_per_file, total_games)
            with open(f'data/games_{i+1}.json', 'w') as f:
                json.dump(all_games[start:end], f)
            print(f"Created file data/games_{i+1}.json with {end - start} games")

        index = {
            "total_games": total_games,
            "total_files": total_files,
            "last_updated": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        }
        with open('data/index.json', 'w') as f:
            json.dump(index, f)
        print("Created index.json file")
        print("Data processing complete!")
        EOF

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update games list" && git push)
