name: Update Games List

on:
  schedule:
    - cron: '0 3 * * *'  # 6утра
  workflow_dispatch:  # 

jobs:
  update-games:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch and process games data
      run: |
        mkdir -p data
        python3 - <<EOF
        import json
        import math
        import requests
        import time

        def fetch_games(offset=0, limit=500):
            url = "https://nu8ichego5ti2suda7prishel111.uhadi.workers.dev"
            params = {"offset": offset, "limit": limit}
            try:
                response = requests.get(url, params=params, timeout=30)
                response.raise_for_status()
                return response.json()
            except requests.RequestException as e:
                print(f"Error fetching games: {e}")
                return None

        print("Fetching games...")
        all_games = []
        offset = 0
        limit = 500
        max_games = 300000

        while len(all_games) < max_games:
            print(f"Fetching batch: offset={offset}, limit={limit}")
            games = fetch_games(offset, limit)
            if games is None or len(games) == 0:
                break
            all_games.extend(games)
            offset += limit
            time.sleep(1)

        total_games = min(len(all_games), max_games)
        all_games = all_games[:total_games]

        print(f"Total games fetched and limited to {max_games}: {total_games}")

        games_per_file = 10000
        total_files = math.ceil(total_games / games_per_file)

        print(f"Creating {total_files} file(s)...")

        for i in range(total_files):
            start = i * games_per_file
            end = min((i + 1) * games_per_file, total_games)
            with open(f'data/games_{i+1}.json', 'w') as f:
                json.dump(all_games[start:end], f)
            print(f"Created file data/games_{i+1}.json with {end - start} games")

        index = {
            "total_games": total_games,
            "total_files": total_files,
            "last_updated": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        }
        with open('data/index.json', 'w') as f:
            json.dump(index, f)
        print("Created index.json file")
        print("Data processing complete!")
        EOF

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git add data
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update games list" && git push)
