name: Update HLTB Data

on:
  schedule:
    - cron: '0 2 * * *' # 5 утра
  workflow_dispatch:

jobs:
  update-hltb-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check index.html content
      run: |
        echo "First 1000 characters of index.html:"
        head -c 1000 index.html
    - name: Update HLTB data
      run: python update_hltb.py
    - name: Check output files
      run: |
        echo "Contents of games_cache.json:"
        cat games_cache.json
        echo "Contents of games_list.json:"
        cat games_list.json
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add games_list.json games_cache.json
        git commit -m "Update game times and cache" -a || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
